# Generated by Django 4.2.4 on 2023-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='верификация'),
        ),
    ]
