# Generated by Django 4.2.4 on 2023-09-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_token_user_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verify',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_key',
            field=models.IntegerField(blank=True, null=True, verbose_name='ключ'),
        ),
    ]
