# Generated by Django 4.2.4 on 2023-08-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_create',
        ),
    ]
