# Generated by Django 4.2.4 on 2023-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
