# Generated by Django 4.2.4 on 2023-09-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='sign_ver',
            field=models.CharField(choices=[('active', 'Active'), ('no_active', 'NoActive')], max_length=50, verbose_name='признак версии'),
        ),
    ]
