# Generated by Django 4.2.4 on 2023-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_version_sign_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_ver',
            field=models.IntegerField(verbose_name='номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sign_ver',
            field=models.CharField(choices=[('active', 'Активна'), ('no_active', 'Не активна')], max_length=50, verbose_name='признак версии'),
        ),
    ]
